branch-defaults:
  develop:
    environment: rubys-admin-dev
  production:
    environment: rubys-admin-prod
deploy:
  artifact: target/application.zip
global:
  application_name: rubys-admin
  branch: null
  default_ec2_keyname: benope_intranet
  default_platform: Corretto 11 running on 64bit Amazon Linux 2
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
