spring:
  security:
    oauth2:
      client:
        registration:
          google:
            scope:
              - openid
              - email
          naver:
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: email
            client-name: Naver
          kakao:
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: account_email
            client-name: Kakao
          apple:
            redirect-uri: 'https://{baseHost}{basePort}{basePath}/{action}/oauth2/code/{registrationId}'
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
              - openid
              - email
            client-name: Apple
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize?response_mode=form_post
            token-uri: https://appleid.apple.com/auth/token
            jwk-set-uri: https://appleid.apple.com/auth/keys
            user-name-attribute: sub
---
spring:
  config:
    activate:
      on-profile:
        - "local"
        - "dev"
        - "test"
        - "prod"
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: none
            client-secret: none
          naver:
            client-id: none
            client-secret: none
          kakao:
            client-id: none
          apple:
            client-id: none
            client-secret: none