sentry:
  exception-resolver-order: -2147483647
  logging:
    minimum-event-level: warn
    minimum-breadcrumb-level: debug
  send-default-pii: true
  traces-sample-rate: 1
  max-request-body-size: ALWAYS
---
spring:
  config:
    activate:
      on-profile:
        - "dev"
sentry:
  dsn: https://6bf97a2f27e343d081dc35f74a759d9e@sentry.benope.link/2
  environment: dev
---
spring:
  config:
    activate:
      on-profile:
        - "prod"
sentry:
  dsn: https://6bf97a2f27e343d081dc35f74a759d9e@sentry.benope.link/2
  environment: prod